# -*- coding: utf-8 -*-
"""
IIR Filter Verification Script — Floating (Python) vs Fixed (RTL)
Generates:
    - stimulus_input.txt (fixed-point input for RTL)
    - iir_params.vh      (Verilog parameters: R1, CO_THETA1, R2, CO_THETA2, CLK_FREQ_HZ)
Plots:
    - Floating input/output
    - Fixed-point input/output
    - RTL output (if available)
"""

import numpy as np
from scipy.signal import lfilter
from math import pi
from pathlib import Path
import matplotlib.pyplot as plt

# --- Import your existing functions (do NOT redefine) ---
from DSP_functions import (
    generate_signal,
    plot_signal_and_spectrum,
    compare_input_output_spectrum,
    FixedPointArray,
)

# ===============================================================
# Helper: compute notch filter coefficients
# ===============================================================
def notch_coeffs_simple(f0, R, Fs):
    theta0 = 2 * pi * f0 / Fs
    b = np.array([1, -2 * np.cos(theta0), 1])
    a = np.array([1, -2 * R * np.cos(theta0), R**2])
    return b, a

# ===============================================================
# MAIN
# ===============================================================
if __name__ == "__main__":
    # ---------------------------
    # Simulation / filter setup
    # ---------------------------
    Fs = 6e6
    f_notches = [1e6, 2.4e6]     # two notch frequencies
    Rs = [0.95, 0.95]            # two damping factors
    stop_time = 3e-3
    fft_len = 8192
    cascade_filters = True        # option to cascade them
    N_plot = 500                  # samples for overlay plots

    # ---------------------------
    # Write Verilog parameter header (S1.30 fixed-point)
    # ---------------------------
    scale = 2**30
    clk_freq_hz = Fs
    R1_fixed = int(Rs[0] * scale)
    R2_fixed = int(Rs[1] * scale)
    CO_THETA1_fixed = int(np.cos(2 * np.pi * f_notches[0] / Fs) * scale)
    CO_THETA2_fixed = int(np.cos(2 * np.pi * f_notches[1] / Fs) * scale)

    with open("iir_params.vh", "w") as f:
        f.write("// Generated by Python (S1.30 fixed-point)\n")
        f.write(f"`define CLK_FREQ_HZ {int(clk_freq_hz)}\n")
        f.write(f"`define R1 32'sd{R1_fixed}\n")
        f.write(f"`define CO_THETA1 32'sd{CO_THETA1_fixed}\n")
        f.write(f"`define R2 32'sd{R2_fixed}\n")
        if CO_THETA2_fixed < 0:
            f.write(f"`define CO_THETA2 -32'sd{abs(CO_THETA2_fixed)}\n")
        else:
            f.write(f"`define CO_THETA2 32'sd{CO_THETA2_fixed}\n")
    print("iir_params.vh written as fixed-point for Verilog testbench!")

    # ---------------------------
    # Generate multi-tone test signal
    # ---------------------------
    freqs = [0.4e6, 2.4e6,5e6]  # frequencies in Hz
    x_in = np.loadtxt("verilog_fixed.txt")

    # ---------------------------
    # Design notch filters
    # ---------------------------
    b1, a1 = notch_coeffs_simple(f_notches[0], Rs[0], Fs)
    b2, a2 = notch_coeffs_simple(f_notches[1], Rs[1], Fs)

    # ---------------------------
    # Apply filters to floating-point input
    # ---------------------------
    y1 = lfilter(b1, a1, x_in)
    if cascade_filters:
        y_python = lfilter(b2, a2, y1)  # cascade second filter
    else:
        y_python = y1                    # only first filter

    # ---------------------------
    # Fixed-point quantization for RTL stimulus & Python fixed-input
    # ---------------------------
    x_fixed = FixedPointArray(x_in, word_length=32, frac_bits=15)
    x_fixed_values = x_fixed.values  # floating-point version of fixed input
    x_fixed_raw = x_fixed.quantize(32, 15).raw_values  # integer values for RTL
   # np.savetxt("stimulus_input.txt", x_fixed_raw, fmt="%d")
    print("Stimulus saved -> stimulus_input.txt")

    # Apply Python filter to fixed-point input
    y_python_fixed_input = lfilter(b1, a1, x_fixed_values)
    if cascade_filters:
        y_python_fixed_input = lfilter(b2, a2, y_python_fixed_input)

    # ---------------------------
    # Load RTL output (if available)
    # ---------------------------
    rtl_output_file = Path("verilogIIR_output.txt")
    if rtl_output_file.exists():
        rtl_raw = np.loadtxt(rtl_output_file, converters={0: lambda x: int(float(x))})
        rtl_output = (FixedPointArray(rtl_raw, word_length=32, frac_bits=15).values) / (2**15)
        print("RTL output converted to floating-point successfully.")
    else:
        rtl_output = None
        print("⚠️ RTL output not found. Skipping comparison.")

    # ---------------------------
    # Plot spectra & signals
    # ---------------------------

    # Floating input/output
    fig_float, axes_float = plot_signal_and_spectrum(rtl_output, Fs, freqs, fft_len=fft_len, stop_time=stop_time)
    axes_float[0].set_title("Python Output - Floating Input (Time Domain)")
    axes_float[1].set_title("Python Output - Floating Input (Frequency Domain)")

    # Fixed-point input/output
    fig_fixed, axes_fixed = plot_signal_and_spectrum(rtl_output, Fs, freqs, fft_len=fft_len, stop_time=stop_time)
    axes_fixed[0].set_title("Python Output - Fixed-point Input (Time Domain)")
    axes_fixed[1].set_title("Python Output - Fixed-point Input (Frequency Domain)")

    # RTL output (if available)
    if rtl_output is not None:
        fig_rtl, axes_rtl = plot_signal_and_spectrum(rtl_output[:600], Fs, freqs, fft_len=fft_len, stop_time=stop_time)
        axes_rtl[0].set_title("RTL Output - Time Domain")
        axes_rtl[1].set_title("RTL Output - Frequency Domain")

        # Compare floating input vs Python floating output
        fig_cmp1 = compare_input_output_spectrum(rtl_output, rtl_output, Fs, Fs, freqs, fft_len, title="INPUT SIGNAL (Floating) vs PYTHON OUTPUT (Floating)")

        # Compare Python floating output vs Python fixed-input output
        fig_cmp2 = compare_input_output_spectrum(rtl_output, rtl_output, Fs, Fs, freqs, fft_len, title="PYTHON OUTPUT (Floating Input) vs PYTHON OUTPUT (Fixed Input)")

        # Compare Python output vs RTL output
        fig_cmp3 = compare_input_output_spectrum(rtl_output, rtl_output[:600], Fs, Fs, freqs, fft_len, title="PYTHON OUTPUT(fixed-point) vs RTL OUTPUT")

        # Overlay time-domain (first N_plot samples)
        plt.figure(figsize=(10, 5))
        plt.plot(y_python[:N_plot], label="Python Output (Floating Input)")
        plt.plot(y_python_fixed_input[:N_plot], label="Python Output (Fixed Input)", alpha=0.7)
        plt.plot(rtl_output[:600], label="RTL Output", alpha=0.5)
        plt.xlabel("Sample Index")
        plt.ylabel("Amplitude")
        plt.title(f"Python & RTL Outputs Comparison (first {N_plot} samples)")
        plt.legend()
        plt.grid(True)
        plt.show()